package com.SM.entity;

import java.util.Date;

public class Server extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.id
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.warehouse_name
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private String warehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.slack_group
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private String slackGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.recipient_slackId
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private String recipientSlackid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.email_address
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.state
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.created_at
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.created_by
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.modified_at
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private Date modifiedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.modified_by
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private Integer modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.delete_flag
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.id
     *
     * @return the value of server.id
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.id
     *
     * @param id the value for server.id
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.warehouse_name
     *
     * @return the value of server.warehouse_name
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.warehouse_name
     *
     * @param warehouseName the value for server.warehouse_name
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.slack_group
     *
     * @return the value of server.slack_group
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public String getSlackGroup() {
        return slackGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.slack_group
     *
     * @param slackGroup the value for server.slack_group
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setSlackGroup(String slackGroup) {
        this.slackGroup = slackGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.recipient_slackId
     *
     * @return the value of server.recipient_slackId
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public String getRecipientSlackid() {
        return recipientSlackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.recipient_slackId
     *
     * @param recipientSlackid the value for server.recipient_slackId
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setRecipientSlackid(String recipientSlackid) {
        this.recipientSlackid = recipientSlackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.email_address
     *
     * @return the value of server.email_address
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.email_address
     *
     * @param emailAddress the value for server.email_address
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.state
     *
     * @return the value of server.state
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.state
     *
     * @param state the value for server.state
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.created_at
     *
     * @return the value of server.created_at
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.created_at
     *
     * @param createdAt the value for server.created_at
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.created_by
     *
     * @return the value of server.created_by
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.created_by
     *
     * @param createdBy the value for server.created_by
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.modified_at
     *
     * @return the value of server.modified_at
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.modified_at
     *
     * @param modifiedAt the value for server.modified_at
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.modified_by
     *
     * @return the value of server.modified_by
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public Integer getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.modified_by
     *
     * @param modifiedBy the value for server.modified_by
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.delete_flag
     *
     * @return the value of server.delete_flag
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.delete_flag
     *
     * @param deleteFlag the value for server.delete_flag
     *
     * @mbg.generated Fri Oct 12 14:22:14 CST 2018
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}