# ------------------------Spring------------------------------
spring:
    profiles:
        active: prod
    thymeleaf:
        cache: false
        mode: HTML5

# ------------------------Mybatis-----------------------------
mybatis:
    type-aliases-package: com.SM.entity