spring:
  datasource:
    url: jdbc:mysql://101.201.212.204:3306/ground_monitoring_new?characterEncoding=utf8&useSSL=false
    username: wanda
    password: 123wanda
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8080